### PR TITLE
Added Tests, Devise methods, link location changes

### PR DESCRIPTION
**Pull request by kathyonu**
Tests have one live Pry binding

### CODE REVIEW

**Comment by bishisht** [comment]
in user.rb i think its better to have admin, guide and traveller guide and traveller are same level users where admin have some more privillege such as getting to /admin backend :)

**Comment by kathyonu** [comment]
admin will see admin stuff.
guides will see guides stuff, guides forms, etc.
travellers will see traveller stuff, forms, etc.

are you saying we have these three roles, only ?
we could add USER for those who access our services or products other than
  these three distinctly different ones of admin, guide, traveller.

**Comment by bishisht** [comment]
For now I don't think we need more roles. :)

**Comment by kathyonu** [comment]
I recommend we stay with `enum role: [:admin, :user, :guide, :traveller]`
Not everyone will be a guide nor a traveller nor an admin, hence we need and want user, for example, when someone buys a product or service, or opens a Stripe Account or Stellar account with us, they wll first and foremost be users. Guide and Traveller role(s) for them may come later, and we simply upgrade them. Guide and Traveller will have more access to the site, more sign_up requirements, more tests.

**Pull request merged**
